version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "chore(deps:github-actions): "
    schedule:
      interval: weekly
      day: friday
      time: "09:00"
      timezone: America/Toronto
    labels:
      - "dependencies"
      - "github-actions"
