version: 2.1
parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
orbs:
  nix: eld/nix@1.1.1
workflows:
  build:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - build_flake
jobs:
  build_flake:
    macos:
      xcode: "14.2.0"
    resource_class: macos.m1.large.gen1
    steps:
      - nix/install:
          planner: macos
      - checkout