name: Install Lix

description: Install the Lix CLI

runs:
  using: "composite"
  steps:
    - shell: bash
      run: curl -sSf -L https://install.lix.systems/lix | sh -s \
        -- install \
        --no-confirm \
        --extra-conf ""trusted-users = root runner""
