name: Install Lix

description: Install the Lix CLI

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        NIX_INSTALLER_EXTRA_CONF="trusted-users = root runner"
        curl -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
