name: Install Lix

runs:
  using: "composite"
  steps:
    - shell: bash
      id: get-system
      run: |
        runners=(Linux_X64 Linux_ARM64 macOS_X64 macOS_ARM64)
        systems=("x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin")

        declare -A system_matrix

        for runner in "${runners[@]}"; do
          system_matrix[$runner]=${systems[i++]}
        done

        runner="$RUNNER_OS_$RUNNER_ARCH"
        systemForRunner=${system_matrix:-$runner}

        echo "system=$systemForRunner" >>"$GITHUB_OUTPUT"
    - uses: DeterminateSystems/nix-installer-action@v13
      with:
        source-url: https://install.lix.systems/lix/lix-installer-${{ steps.get-system.outputs.system }}
        diagnostic-endpoint: ""
