name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Build flake
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN }}