name: Build attributes

on:
  workflow_call:

permissions: {}

jobs:
  attribute-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: "${{ steps.set-matrix.outputs.matrix }}"
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_USER_SSH_KEY }}
      - name: Install Lix
        uses: ./.github/actions/install-lix
      - name: Set up cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
        with:
          diagnostic-endpoint: ""
      - id: set-matrix
        name: Generate attribute matrix
        run: |
          set -Eeu
          echo "matrix=$(nix eval --json '.#githubActions.matrix')" >> "$GITHUB_OUTPUT"
  
  build-attribute:
    name: "${{ matrix.name }}"
    needs: attribute-matrix
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.attribute-matrix.outputs.matrix) }}
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_USER_SSH_KEY }}
      - name: Install Lix
        uses: ./.github/actions/install-lix
      - name: Set up cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
        with:
          diagnostic-endpoint: ""
      - name: Build "${{ matrix.attr }}"
        run: |
          nix build .#${{ matrix.attr }}

  collect:
    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
    needs: [build-attribute]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all matrix job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
