name: Build attributes

on:
  workflow_call:

permissions: {}

jobs:
  attribute-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: "${{ steps.set-matrix.outputs.matrix }}"
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4

      - id: set-matrix
        name: Generate attribute matrix
        run: |
          set -Eeu
          echo "matrix=$(nix eval --json '.#githubActions.matrix')" >> "$GITHUB_OUTPUT"
  
  attribute-build:
    name: "${{ matrix.attr }}"
    needs: attribute-matrix
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.attribute-matrix.outputs.matrix) }}
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Build "${{ matrix.attr }}"
        run: |
          NIXPKGS_ALLOW_UNFREE=1 nix build .#${{ matrix.attr }} --impure
