name: Build attributes

on:
  workflow_call:

permissions: {}

jobs:
  attribute-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: "${{ steps.set-matrix.outputs.matrix }}"
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v6

      - id: set-matrix
        name: Generate attribute matrix
        run: |
          set -Eeu
          echo "matrix=$(nix eval --json '.#githubActions.matrix')" >> "$GITHUB_OUTPUT"
  
  build-attribute:
    name: "${{ matrix.attr }}"
    needs: attribute-matrix
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.attribute-matrix.outputs.matrix) }}
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v6

      - name: Build "${{ matrix.attr }}"
        run: |
          NIXPKGS_ALLOW_UNFREE=1 nix build .#${{ matrix.attr }} --impure

  collect:
    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
    needs: [build-attribute]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all matrix job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
