env:
  CACHIX_CACHE_NAME: remi-gelinas-nix
  EXTRA_SUBSTITUTERS: nix-community

on:
  push:
    branches:
      - trunk

permissions: {}

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      CACHIX_CACHE_NAME: ${{ steps.set-env.outputs.CACHIX_CACHE_NAME }}
      EXTRA_SUBSTITUTERS: ${{ steps.set-env.outputs.EXTRA_SUBSTITUTERS }}
    steps:
      - id: set-env
        run: |
          echo "CACHIX_CACHE_NAME=${{ env.CACHIX_CACHE_NAME }}" >> "$GITHUB_OUTPUT"
          echo "EXTRA_SUBSTITUTERS=${{ env.EXTRA_SUBSTITUTERS }}" >> "$GITHUB_OUTPUT"

  build-attributes:
    needs: set-env
    uses: ./.github/workflows/build-attributes.yaml
    permissions:
      contents: read
    with:
      cache-name: ${{ needs.set-env.outputs.CACHIX_CACHE_NAME }}
      extra-caches: ${{ needs.set-env.outputs.EXTRA_SUBSTITUTERS }}
      cache: true
      pin: true
    secrets: inherit