name: CI

on:
  pull_request:
    branches:
      - trunk

permissions: {}

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    permissions:
      contents: read
    secrets: inherit

  build-attributes:
    uses: ./.github/workflows/build-attributes.yaml
    permissions:
      contents: read
    secrets: inherit

  collect:
    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
    needs: [build-attributes]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all matrix job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1