name: Flake check

on:
  pull_request:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"

jobs:
  check:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v21
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          install_url: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.17.0pre20230609_03f9ff6/install
          extra-nix-config: |
            substituters = https://cache.nixos.org https://nix-community.cachix.org https://remi-gelinas-nix.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= remi-gelinas-nix.cachix.org-1:nj3SWe8g0jlpzvzvgE6znxY21XaONHxJ1qZQQsHBBNA=

      - name: Check flake
        run: |
          nix flake check