name: Flake check

env:
  NIX_INSTALL_URL: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.17.0pre20230609_03f9ff6/install
  CACHIX_CACHE_NAME: remi-gelinas-nix
  EXTRA_CACHIX_SUBSTITUTERS: https://nix-community.cachix.org
on:
  pull_request:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"

jobs:
  check:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
          install_url: '${{ env.NIX_INSTALL_URL }}'
          extra-nix-config: |
            substituters = https://cache.nixos.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      
      - uses: cachix/cachix-action@v12
        with:
          name: '${{ env.CACHIX_CACHE_NAME }}'
          authToken: '${{ secrets.CACHIX_TOKEN }}'
          extraPullNames: '${{ EXTRA_CACHIX_SUBSTITUTERS }}'

      - name: Check flake
        run: |
          cachix watch-exec $CACHIX_CACHE_NAME -- nix flake check