name: Flake input check

on:
  pull_request:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"

jobs:
  check_nixpkgs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Check nixpkgs flake inputs
        uses: DeterminateSystems/flake-checker-action@v4