env:
  CACHIX_CACHE_NAME: remi-gelinas-nix
  EXTRA_SUBSTITUTERS: nix-community

on:
  push:
    branches:
      - trunk

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  flake-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4

      - uses: cachix/cachix-action@v14
        with:
          name: '${{ env.CACHIX_CACHE_NAME }}'
          authToken: '${{ secrets.CACHIX_TOKEN }}'
          skipPush: true
          extraPullNames: "${{ env.EXTRA_SUBSTITUTERS }}"

      - name: Build and cache flake inputs
        run: |
          nix flake archive \
            --json \
          | jq -r '.path,(.inputs|to_entries[].value.path)' \
          | cachix push ${{ env.CACHIX_CACHE_NAME }}
