name: Flake builder

env:
  NIX_INSTALL_URL: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.17.0pre20230609_03f9ff6/install
  CACHIX_CACHE_NAME: remi-gelinas-nix
  EXTRA_NIX_CONFIG: |
    auto-optimise-store = true
    experimental-features = nix-command flakes
    substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://remi-gelinas-nix.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= remi-gelinas-nix.cachix.org-1:nj3SWe8g0jlpzvzvgE6znxY21XaONHxJ1qZQQsHBBNA=

on:
  push:
    branches:
      - "remi-gelinas/flake-builder-workflow"
  # pull_request:
  #   branches:
  #     - "trunk"
  #   paths:
  #     - "**"
  #     - "!**.md"
  #     - "!**.org"
  # push:
  #   branches:
  #     - "trunk"
  #   paths:
  #     - "**"
  #     - "!**.md"
  #     - "!**.org"

jobs:
  generate-system-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system:
          - arch: x86_64-linux
            runner: ubuntu-latest
          - arch: x86_64-darwin
            runner: macos-latest
    steps:
      - run: |
          matrix=$((
            echo '${{ toJSON(matrix) }}'
          ) | jq -c .)
          echo "$matrix" > matrix
        id: matrix

      - run: |
          pwd
          echo $GITHUB_WORKSPACE

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ hashFiles('./matrix') }}
          path: matrix
          if-no-files-found: warn

  check-system-matrix:
    runs-on: ubuntu-latest
    needs: [ generate-system-matrix ]
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/download-artifact@v3
      - id: matrix
        run: |
          ls
          matrix="$(cat */matrix | jq -c --slurp .)"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"