name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * FRI'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Run self-hosted Renovate
        uses: renovatebot/github-action@063e0c946b9c1af35ef3450efc44114925d6e8e6 # v40.1.11
        with:
          configurationFile: .github/renovate.json5
          token: '${{ steps.get_token.outputs.token }}'
