name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * FRI'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          installation_id: '${{ secrets.RENOVATE_APP_INSTALLATION_ID }}'
          app_id: ${{ secrets.RENOVATE_APP_ID }}

      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Run self-hosted Renovate
        uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        with:
          configurationFile: .github/renovate.json5
          token: '${{ steps.get_token.outputs.token }}'
